apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: goapp
  namespace: dev
spec:
  targetNamespace: dev
  install:
    createNamespace: true
  interval: 1m
  chart:
    spec:
      chart: ./charts
      sourceRef:
        kind: GitRepository
        name: goapp
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: himanshu162pnt723/goapp
      tag: "20251004032314" # {"$imagepolicy": "flux-system:goapp:tag"}
    service:
      type: NodePort
      port: 8080
