apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: goapp
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    strategy: Setters
  git:
    checkout:
      ref:
        branch: master
    push:
      branch: master
    commit:
      author:
        name: fluxcdbot
        email: flux@example.com
      messageTemplate: |
        will test later
