apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      hostNetwork: true                     # Bind pods directly to host network
      dnsPolicy: ClusterFirstWithHostNet    # Required for hostNetwork pods
      ingressClassByName: true              # Ensure ingressClassName works
      config:
        http2: true
        http2-push: "on"
        http2-push-preload: "on"
      service:
        type: ClusterIP                     # No LoadBalancer needed
        externalTrafficPolicy: Local
