apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 30m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      ingressClassByName: true
      service:
        type: NodePort
        externalTrafficPolicy: Local
        nodePorts:
          http: 30080
          https: 30443
      config:
        use-forwarded-headers: "true"
        proxy-real-ip-cidr: "0.0.0.0/0"
